# Automação Web e Busca de Informações com Python

#### Desafio: 

Trabalhamos em uma importadora e o preço dos nossos produtos é vinculado a cotação de:
- Dólar
- Euro
- Ouro

Precisamos pegar na internet, de forma automática, a cotação desses 3 itens e saber quanto devemos cobrar pelos nossos produtos, considerando uma margem de contribuição que temos na nossa base de dados.

Base de Dados: https://drive.google.com/drive/folders/1o2lpxoi9heyQV1hIlsHXWSfDkBPtze-V?usp=sharing

Para isso, vamos criar uma automação web:

- Usaremos o selenium
- Importante: baixar o webdriver

In [31]:
# colocar o driver no diretório de instalação do Python no computador.
# google chrome -> chromedriver
# firefox -> geckodriver

In [32]:
# Passo 1: Pegar a cotação do dólar
# Passo 2: Pegar a cotação do euro
# Passo 3: Pegar a cotação do ouro
# Passo 4: Importar a lista de produtos
# Passo 5: Recalcular o preço de cada produto
# Passo 6: Salvar os novos preços dos produtos

In [33]:
# Sempre que utilizar o selenium, é necessário importar dois pacotes da biblioteca

# from selenium import webdriver
# from selenium.webdriver.common.keys import Keys

In [34]:
# GOOGLE CHROME

from selenium import webdriver
from selenium.webdriver.common.keys import Keys

# abrir um navegador
navegador = webdriver.Chrome()
navegador.get('https://www.google.com/')

# Passo 1: Pegar a cotação do dólar
navegador.find_element_by_xpath(
    '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys("cotação dólar")
navegador.find_element_by_xpath(
    '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys(Keys.ENTER)
cotacao_dolar = navegador.find_element_by_xpath(
    '//*[@id="knowledge-currency__updatable-data-column"]/div[1]/div[2]/span[1]').get_attribute('data-value')
print(cotacao_dolar)

# Passo 2: Pegar a cotação do euro
navegador.get('https://www.google.com/')
navegador.find_element_by_xpath(
    '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys("cotação euro")
navegador.find_element_by_xpath(
    '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys(Keys.ENTER)
cotacao_euro = navegador.find_element_by_xpath(
    '//*[@id="knowledge-currency__updatable-data-column"]/div[1]/div[2]/span[1]').get_attribute('data-value')
print(cotacao_euro)

# Passo 3: Pegar a cotação do ouro
navegador.get('https://www.melhorcambio.com/ouro-hoje')
cotacao_ouro = navegador.find_element_by_xpath(
    '//*[@id="comercial"]').get_attribute('value')
cotacao_ouro = cotacao_ouro.replace(",", ".")
print(cotacao_ouro)

4.9147
5.870068533
280.47

In [35]:
# MOZILLA FIREFOX
# Dá algum bug, não saquei o que. Vou deixar tudo como comentário.

# from selenium import webdriver
# from selenium.webdriver.common.keys import Keys

# # abrir um navegador
# navegador = webdriver.Firefox()
# navegador.get('https://www.google.com/')

# # Passo 1: Pegar a cotação do dólar
# navegador.find_element_by_xpath(
#     '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys("cotação dólar")
# navegador.find_element_by_xpath(
#     '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys(Keys.ENTER)

# cotacao_dolar = navegador.find_element_by_xpath(
#     "/html/body/div[7]/div/div[9]/div[1]/div/div[2]/div[2]/div/div/div[1]/div/div/div/div/div[1]/div/div[1]/div[1]/div[2]/span[1]").get_attribute('data-value')
# print(cotacao_dolar)

### Agora vamos atualiza a nossa base de preços com as novas cotações

- Importando a base de dados

In [36]:
# Passo 4: Importar a lista de produtos
import pandas as pd

tabela = pd.read_excel('Produtos.xlsx')
display(tabela)

,Produtos,Preço Base Original,Moeda,Cotação,Preço Base Reais,Margem,Preço Final
0,Câmera Canon,999.99,Dólar,5,4999.95,1.40,6999.930
1,Carro Renault,4500.00,Euro,6,27000.00,2.00,54000.000
2,Notebook Dell,899.99,Dólar,5,4499.95,1.70,7649.915
3,IPhone,799.00,Dólar,5,3995.00,1.70,6791.500
4,Carro Fiat,3000.00,Euro,6,18000.00,1.90,34200.000
5,Celular Xiaomi,480.48,Dólar,5,2402.40,2.00,4804.800
6,Joia 20g,20.00,Ouro,350,7000.00,1.15,8050.000

- Atualizando os preços e o cálculo do Preço Final

In [37]:
# Passo 5: Recalcular o preço de cada produto
# atualizar a cotação
# nas linhas onde na coluna "Moeda" = Dólar

# tabela.loc[linha, coluna] = float(cotacao)
tabela.loc[tabela["Moeda"] == "Dólar", "Cotação"] = float(cotacao_dolar)
tabela.loc[tabela["Moeda"] == "Euro", "Cotação"] = float(cotacao_euro)
tabela.loc[tabela["Moeda"] == "Ouro", "Cotação"] = float(cotacao_ouro)

# atualizar o preço base reais (preço base original * cotação)
tabela["Preço Base Reais"] = tabela["Preço Base Original"] * tabela["Cotação"]

# atualizar o preço final(preço base reais * margem)
tabela["Preço Final"] = tabela["Preço Base Reais"] * tabela["Margem"]

display(tabela)

# Passo 6: Salvar os novos preços dos produtos

,Produtos,Preço Base Original,Moeda,Cotação,Preço Base Reais,Margem,Preço Final
0,Câmera Canon,999.99,Dólar,4.914700,4914.650853,1.40,6880.511194
1,Carro Renault,4500.00,Euro,5.870069,26415.308399,2.00,52830.616797
2,Notebook Dell,899.99,Dólar,4.914700,4423.180853,1.70,7519.407450
3,IPhone,799.00,Dólar,4.914700,3926.845300,1.70,6675.637010
4,Carro Fiat,3000.00,Euro,5.870069,17610.205599,1.90,33459.390638
5,Celular Xiaomi,480.48,Dólar,4.914700,2361.415056,2.00,4722.830112
6,Joia 20g,20.00,Ouro,280.470000,5609.400000,1.15,6450.810000

### Agora vamos exportar a nova base de preços atualizada

In [38]:
# Passo 6: Salvar os novos preços dos produtos
tabela.to_excel("Produto Novo.xlsx", index=False)